# Generated by Django 5.1.1 on 2024-12-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='tutormore',
            name='specialization',
            field=models.TextField(default='Math', max_length=1024),
        ),
        migrations.AddField(
            model_name='tutormore',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default='Math'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_grade',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year'), (4, 'Fourth year')], default=1),
        ),
    ]
