# Generated by Django 5.1.1 on 2024-12-04 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_user_phone_number_tutormore_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('location', models.CharField(choices=[('Antwerp', 'Antwerp'), ('Ghent', 'Ghent'), ('Charleroi', 'Charleroi'), ('Liège', 'Liège'), ('Brussels', 'Brussels'), ('Bruges', 'Bruges'), ('Namur', 'Namur'), ('Leuven', 'Leuven'), ('Mons', 'Mons'), ('Aalst', 'Aalst'), ('Mechelen', 'Mechelen'), ('La Louvière', 'La Louvière'), ('Kortrijk', 'Kortrijk'), ('Hasselt', 'Hasselt'), ('Ostend', 'Ostend'), ('Sint-Niklaas', 'Sint-Niklaas'), ('Tournai', 'Tournai'), ('Genk', 'Genk'), ('Seraing', 'Seraing'), ('Roeselare', 'Roeselare')], max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=100)),
                ('about_tutor', models.TextField(blank=True, max_length=2056)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='accounts.tutormore')),
            ],
        ),
    ]
