import mockTutor1 from '../assets/Mock/mock_tutor_1.jpg';
import mockTutor2 from '../assets/Mock/mock_tutor_2.jpg';
import mockTutor3 from '../assets/Mock/mock_tutor_3.jpg';
import mockTutor4 from '../assets/Mock/mock_tutor_4.jpg';
import mockTutor5 from '../assets/Mock/mock_tutor_5.jpg';
import mockTutor6 from '../assets/Mock/mock_tutor_6.jpeg';
import mockTutor7 from '../assets/Mock/mock_tutor_7.jpg';
import mockTutor8 from '../assets/Mock/mock_tutor_8.jpg';
import mockTutor9 from '../assets/Mock/mock_tutor_9.jpeg';
import mockTutor10 from '../assets/Mock/mock_tutor_10.jpg';



const tutors = [
    {
      name: 'Andrii Pupkin',
      subject: 'Physics',
      rating: 5,
      price: '30€',
      response: 1,
      lessonDuration: '50 min',
      bio: `An experienced, knowledgeable teacher will help you learn physics, study theory, learn to solve problems, think, analyze and draw conclusions. I work as a teacher of physics and computer science, I have 30 years of teaching experience, I have my own developments that are posted on various educational sites, I undergo annual training both in my specialty and in pedagogy and psychology.`,
      location: 'Only online',
      university: 'Université catholique de Louvain',
      year: '3rd year',
      languages: 'English C1, German B2, Ukrainian C1',
      photo: mockTutor1,
    },
    {
      name: 'Ihor Myshyk',
      subject: 'Physics',
      rating: 4.9,
      price: '50€',
      response: 10,
      lessonDuration: '30 min',
      bio: `Tutor for mathematics, physics, school, admission to university — Deep and accessible presentation of material, enthusiasm, optimism, block system, emphasis on practice, taking into account the psychological characteristics of the student. I have 16 years in educational institutions - school, lyceum, gymnasium, and 12 years - tutoring.`,
      location: 'Brussels, online',
      university: 'Universiteit Gent',
      year: '3rd year',
      languages: 'English',
      photo: mockTutor2,
    },
    {
      name: 'Olena Kravets',
      subject: 'Mathematics',
      rating: 4.8,
      price: '40€',
      response: 2,
      lessonDuration: '60 min',
      bio: `I am a math tutor with a passion for helping students achieve their academic goals. With 10 years of experience, I tailor my lessons to fit individual learning needs.`,
      location: 'Kyiv, online',
      university: 'Kyiv National University',
      year: '2nd year',
      languages: 'Ukrainian, English B2',
      photo: mockTutor3,
    },
    {
      name: 'Julia Sokol',
      subject: 'Chemistry',
      rating: 5,
      price: '35€',
      response: 3,
      lessonDuration: '45 min',
      bio: `Passionate about chemistry, I strive to make it interesting and understandable for students. I specialize in preparation for exams and university admission.`,
      location: 'Only online',
      university: 'University of Cambridge',
      year: '4th year',
      languages: 'English, French B1',
      photo: mockTutor4,
    },
    {
      name: 'Dmytro Vasyliv',
      subject: 'History',
      rating: 4.7,
      price: '25€',
      response: 5,
      lessonDuration: '50 min',
      bio: `Experienced history tutor, helping students understand world and local history through engaging lessons and discussions.`,
      location: 'Lviv, online',
      university: 'Lviv Polytechnic University',
      year: 'Graduate',
      languages: 'Ukrainian, English C1',
      photo: mockTutor5,
    },
    {
      name: 'Sophia Reims',
      subject: 'Biology',
      rating: 4.9,
      price: '45€',
      response: 2,
      lessonDuration: '60 min',
      bio: `Biology is fascinating, and I love sharing my enthusiasm with students. Let's explore life sciences together!`,
      location: 'Paris, online',
      university: 'Sorbonne University',
      year: '3rd year',
      languages: 'French, English B2',
      photo: mockTutor6,
    },
    {
      name: 'Marco Rossi',
      subject: 'Italian',
      rating: 5,
      price: '30€',
      response: 4,
      lessonDuration: '40 min',
      bio: `Learn Italian with an enthusiastic native speaker! Customized lessons to improve conversational skills and grammar.`,
      location: 'Rome, online',
      university: 'Sapienza University of Rome',
      year: '4th year',
      languages: 'Italian, English C1',
      photo: mockTutor7,
    },
    {
      name: 'Kim Jon Ung',
      subject: 'Chinese',
      rating: 4.8,
      price: '20€',
      response: 1,
      lessonDuration: '55 min',
      bio: `Experienced tutor teaching Chinese language and culture to non-native speakers with interactive methods.`,
      location: 'Benjin, online',
      university: 'Benjin State University',
      year: 'Graduate',
      languages: 'Chinese, English B2',
      photo: mockTutor8,
    },
    {
      name: 'Carlos Mendes',
      subject: 'Portuguese',
      rating: 4.9,
      price: '25€',
      response: 6,
      lessonDuration: '50 min',
      bio: `Native Portuguese speaker with 5 years of teaching experience. Improve your speaking and writing skills quickly!`,
      location: 'Lisbon, online',
      university: 'University of Lisbon',
      year: 'Graduate',
      languages: 'Portuguese, Spanish, English B1',
      photo: mockTutor9,
    },
    {
      name: 'Liam O’Connor',
      subject: 'English Literature',
      rating: 5,
      price: '60€',
      response: 3,
      lessonDuration: '70 min',
      bio: `Let's explore the beauty of English literature together! I specialize in classic and modern works, analysis, and essay writing.`,
      location: 'Dublin, online',
      university: 'Trinity College Dublin',
      year: '3rd year',
      languages: 'English',
      photo: mockTutor10,
    },
    
  ];
  
  export default tutors;