name: End to end tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Run E2E Tests
      run: docker compose run --build --rm e2e-tests

    - name: Upload E2E screenshots as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: e2e_tests_screenshots
        path: e2e_tests_screenshots/

    - name: Stop containers
      if: always()
      run: docker compose down

