name: Automated tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: python:3.10

    services:
      postgres:
        image: postgres:14.8-alpine3.18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: django
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - "5432:5432"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Install pytest
        run: |
          pip install pytest 
          pip install pytest-django

      - name: Run Tests
        working-directory: ./backend/tests
        run: pytest
        env:
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASS: django
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DJANGO_SETTINGS_MODULE: backend.settings
