name: Automated tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: python:3.10

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: django
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          -5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Tests
        run: |
          pytest
        env:
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASS: django
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
